version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Interface Type Module

  Manages Interface Type

  Location in GUI:
  `Fabric` » `Inventory` » `Pod XXX` » `Node XXX` » `Interface`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
